name: Earthly CI

on:
  push:
    branches: [ main ]


jobs:
  earthly-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - name: Run earthly +all
        run: earthly --ci +all

