name: Earthly CI

on:
  push:
    branches: [ main ]


jobs:
  earthly-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - name: Run the build
        run: earthly +build

      - name: Test the code
        run: earthly +pytest

      - name: Fix format and check the code
        run: earthly +ruff-check

