name: Earthly CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - name: Run the build
        run: earthly +build

  pytest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - name: Run tests
        run: earthly +pytest

  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - name: Run ruff check
        run: earthly +ruff-check
